
import java.awt.Color;

/**
 *
 * @author Sam
 */
public class DenialAppealSystem extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public DenialAppealSystem() {
        initComponents();
        loginButton.requestFocus();
        connErr.setVisible(false);
        denialList.setVisible(false);
        letterGenPanel.setVisible(false);
        letterGenTransBgPanel.setBackground(new Color(255,255,255,140));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        loginPanel = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        userIcon = new javax.swing.JLabel();
        connErr = new javax.swing.JLabel();
        denialList = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        denialListPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        patientNameLabel = new javax.swing.JLabel();
        insuranceNameLabel = new javax.swing.JLabel();
        denialReasonLabel = new javax.swing.JLabel();
        dosLabel = new javax.swing.JLabel();
        denialScrollPane = new javax.swing.JScrollPane();
        denialListList = new javax.swing.JList<>();
        letterGenPanel = new javax.swing.JPanel();
        welcome1 = new javax.swing.JLabel();
        logoutButton1 = new javax.swing.JButton();
        letterGenTransBgPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Denial Appeal System - Login");
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1150, 800));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 255, 204));

        loginPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginPanel.setFocusable(false);
        loginPanel.setOpaque(false);

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setText("Username");
        username.setBorder(null);
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        username.setSelectionColor(new java.awt.Color(0, 204, 204));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });

        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setText("Password");
        password.setToolTipText("");
        password.setBorder(null);
        password.setSelectionColor(new java.awt.Color(0, 204, 204));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(0, 153, 153));
        loginButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(102, 102, 102));
        loginButton.setText("Login");
        loginButton.setOpaque(false);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginButtonClicked(evt);
            }
        });

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user4.png"))); // NOI18N
        userIcon.setMaximumSize(new java.awt.Dimension(150, 150));
        userIcon.setPreferredSize(new java.awt.Dimension(193, 193));

        connErr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        connErr.setText(" Login Error! Please try again.");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(586, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                .addComponent(connErr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(421, 421, 421))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(515, 515, 515))))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connErr))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        denialList.setOpaque(false);

        welcome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcome.setForeground(new java.awt.Color(102, 102, 102));
        welcome.setText("Welcome, ");

        logoutButton.setBackground(new java.awt.Color(0, 153, 153));
        logoutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(102, 102, 102));
        logoutButton.setText("Logout");
        logoutButton.setOpaque(false);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                returnToLogin(evt);
            }
        });

        denialListPanel.setBackground(new java.awt.Color(204, 255, 204));
        denialListPanel.setOpaque(false);

        titlePanel.setBackground(new java.awt.Color(0, 153, 153));

        patientNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        patientNameLabel.setForeground(new java.awt.Color(204, 255, 204));
        patientNameLabel.setText("Patient Name");
        patientNameLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        insuranceNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insuranceNameLabel.setForeground(new java.awt.Color(204, 255, 204));
        insuranceNameLabel.setText("Insurance");

        denialReasonLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        denialReasonLabel.setForeground(new java.awt.Color(204, 255, 204));
        denialReasonLabel.setText("Denial Reason");

        dosLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dosLabel.setForeground(new java.awt.Color(204, 255, 204));
        dosLabel.setText("DOS");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(patientNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insuranceNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(denialReasonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(patientNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addComponent(insuranceNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(denialReasonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dosLabel))
        );

        denialScrollPane.setBorder(null);
        denialScrollPane.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        denialScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        denialListList.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        denialListList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        denialListList.setForeground(new java.awt.Color(0, 153, 153));
        denialListList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Patient1", "Patient2", "Patient3", "Patient4", "Patient5", "Patient6", "Patient7", "Patient8", "Patient9", "Patient10", "Patient1", "Patient2", "Patient3", "Patient4", "Patient5", "Patient6", "Patient7", "Patient8", "Patient9", "Patient10", "Patient1", "Patient2", "Patient3", "Patient4", "Patient5", "Patient6", "Patient7", "Patient8", "Patient9", "Patient10", "Patient1", "Patient2", "Patient3", "Patient4", "Patient5", "Patient6", "Patient7", "Patient8", "Patient9", "Patient10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        denialListList.setFixedCellHeight(20);
        denialListList.setSelectionBackground(new java.awt.Color(0, 204, 204));
        denialListList.setValueIsAdjusting(true);
        denialListList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                denialListListMouseClicked(evt);
            }
        });
        denialScrollPane.setViewportView(denialListList);

        javax.swing.GroupLayout denialListPanelLayout = new javax.swing.GroupLayout(denialListPanel);
        denialListPanel.setLayout(denialListPanelLayout);
        denialListPanelLayout.setHorizontalGroup(
            denialListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(denialScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        denialListPanelLayout.setVerticalGroup(
            denialListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(denialListPanelLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(denialScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout denialListLayout = new javax.swing.GroupLayout(denialList);
        denialList.setLayout(denialListLayout);
        denialListLayout.setHorizontalGroup(
            denialListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(denialListLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(denialListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(denialListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(denialListLayout.createSequentialGroup()
                        .addComponent(welcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        denialListLayout.setVerticalGroup(
            denialListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, denialListLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(denialListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(denialListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        letterGenPanel.setOpaque(false);
        letterGenPanel.setPreferredSize(new java.awt.Dimension(1299, 841));

        welcome1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcome1.setForeground(new java.awt.Color(102, 102, 102));
        welcome1.setText("Welcome, ");

        logoutButton1.setBackground(new java.awt.Color(0, 153, 153));
        logoutButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutButton1.setForeground(new java.awt.Color(102, 102, 102));
        logoutButton1.setText("Logout");
        logoutButton1.setOpaque(false);
        logoutButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnToLogin(evt);
            }
        });

        letterGenTransBgPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout letterGenTransBgPanelLayout = new javax.swing.GroupLayout(letterGenTransBgPanel);
        letterGenTransBgPanel.setLayout(letterGenTransBgPanelLayout);
        letterGenTransBgPanelLayout.setHorizontalGroup(
            letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        letterGenTransBgPanelLayout.setVerticalGroup(
            letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout letterGenPanelLayout = new javax.swing.GroupLayout(letterGenPanel);
        letterGenPanel.setLayout(letterGenPanelLayout);
        letterGenPanelLayout.setHorizontalGroup(
            letterGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letterGenPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(letterGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(letterGenTransBgPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(letterGenPanelLayout.createSequentialGroup()
                        .addComponent(welcome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        letterGenPanelLayout.setVerticalGroup(
            letterGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letterGenPanelLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(letterGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letterGenTransBgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(denialList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(letterGenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(denialList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(letterGenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(kGradientPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        if(username.getText().equals("Username")){
            username.setText("");
            username.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        if(username.getText().equals("")){
            username.setText("Username");
            username.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        if(String.valueOf(password.getPassword()).equals("Password")){
            password.setText("");
            password.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        if(String.valueOf(password.getPassword()).equals("")){
            password.setText("Password");
            password.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_passwordFocusLost

    private void LoginButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonClicked

        // This is where we take the username and password strings to connect to the DB
        // will need to add a new class for the 'controller' with MVC format
        
        // add code for if connection to db = true, loginpanel.setvisible(false)
        // currently always showing the result of a true db connection
        loginPanel.setVisible(false);
        denialList.setVisible(true);
        setTitle("Denial Appeal System - Denial List");
        
        
        
        //if connection could not be established, connErr.setVisible(true);
        
    }//GEN-LAST:event_LoginButtonClicked

    private void returnToLogin(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnToLogin
        // TODO add your handling code here:
        // will need to add component that disconnects from db
        if (denialList.isVisible()){
            denialList.setVisible(false);
            setTitle("Denial Appeal System - Login");
            loginPanel.setVisible(true);
        }
        if (letterGenPanel.isVisible()){
            letterGenPanel.setVisible(false);
            setTitle("Denial Appeal System - Login");
            loginPanel.setVisible(true);
        }
    }//GEN-LAST:event_returnToLogin

    private void denialListListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_denialListListMouseClicked
        // TODO add your handling code here:
        javax.swing.JList<String> tmpClickItem = (javax.swing.JList) evt.getSource();
        if (evt.getClickCount()== 2){
            denialList.setVisible(false);
            letterGenPanel.setVisible(true);
            setTitle("Denial Appeal System - Letter Generation");
            int index = tmpClickItem.locationToIndex(evt.getPoint());
            if (index >= 0) {
                Object o = tmpClickItem.getModel().getElementAt(index);
                System.out.println("Double-clicked on: " + o.toString()); //remove with functionality, temporary placeholder of list item that was selected
            }
        }
        
    }//GEN-LAST:event_denialListListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DenialAppealSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DenialAppealSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DenialAppealSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DenialAppealSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DenialAppealSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel connErr;
    private javax.swing.JPanel denialList;
    private javax.swing.JList<String> denialListList;
    private javax.swing.JPanel denialListPanel;
    private javax.swing.JLabel denialReasonLabel;
    private javax.swing.JScrollPane denialScrollPane;
    private javax.swing.JLabel dosLabel;
    private javax.swing.JLabel insuranceNameLabel;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPanel letterGenPanel;
    private javax.swing.JPanel letterGenTransBgPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton logoutButton1;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel userIcon;
    private javax.swing.JTextField username;
    private javax.swing.JLabel welcome;
    private javax.swing.JLabel welcome1;
    // End of variables declaration//GEN-END:variables
}
