
import java.awt.Color;


/**
 *
 * @author Sam
 */
public class DenialAppealSystem extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public DenialAppealSystem() {
        initComponents();
        loginButton.requestFocus();
        connErr.setVisible(false);
        denialList.setVisible(false);
        letterGenPanel.setVisible(false);
        letterGenTransBgPanel.setBackground(new Color(255,255,255,140));
        jSeparator1.setBackground(new Color(255,255,255,0));
        jSeparator2.setBackground(new Color(255,255,255,0));
        saveAppealReasonCheckBox.setBackground(new Color(255,255,255,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        loginPanel = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        userIcon = new javax.swing.JLabel();
        connErr = new javax.swing.JLabel();
        denialList = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        denialListPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        patientNameLabel = new javax.swing.JLabel();
        insuranceNameLabel = new javax.swing.JLabel();
        denialReasonLabel = new javax.swing.JLabel();
        dosLabel = new javax.swing.JLabel();
        denialScrollPane = new javax.swing.JScrollPane();
        denialListList = new javax.swing.JList<>();
        letterGenPanel = new javax.swing.JPanel();
        welcome1 = new javax.swing.JLabel();
        logoutButton1 = new javax.swing.JButton();
        letterGenTransBgPanel = new javax.swing.JPanel();
        ptNameLabel = new javax.swing.JLabel();
        ptDosLabel = new javax.swing.JLabel();
        procLabel = new javax.swing.JLabel();
        dxLabel = new javax.swing.JLabel();
        attPhysLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        insCoLabel = new javax.swing.JLabel();
        insCoAdd1 = new javax.swing.JLabel();
        insCoAdd2 = new javax.swing.JLabel();
        insCoAdd3 = new javax.swing.JLabel();
        insCoLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        ptDenialReasonLabel = new javax.swing.JLabel();
        preGenAppealReasonLabel = new javax.swing.JLabel();
        preGenAppealReasons = new javax.swing.JComboBox<>();
        preGenAppealReasonLabel1 = new javax.swing.JLabel();
        newAppealTitleTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        saveAppealReasonCheckBox = new javax.swing.JCheckBox();
        backButton = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        coInsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Denial Appeal System - Login");
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1150, 800));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 255, 204));

        loginPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginPanel.setFocusable(false);
        loginPanel.setOpaque(false);

        username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        username.setForeground(new java.awt.Color(153, 153, 153));
        username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        username.setText("Username");
        username.setBorder(null);
        username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        username.setSelectionColor(new java.awt.Color(0, 204, 204));
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });

        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        password.setText("Password");
        password.setToolTipText("");
        password.setBorder(null);
        password.setSelectionColor(new java.awt.Color(0, 204, 204));
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(0, 153, 153));
        loginButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(102, 102, 102));
        loginButton.setText("Login");
        loginButton.setOpaque(false);
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LoginButtonClicked(evt);
            }
        });

        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user4.png"))); // NOI18N
        userIcon.setMaximumSize(new java.awt.Dimension(150, 150));
        userIcon.setPreferredSize(new java.awt.Dimension(193, 193));

        connErr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        connErr.setText(" Login Error! Please try again.");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap(586, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                .addComponent(connErr)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(421, 421, 421))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(515, 515, 515))))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(userIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connErr))
                .addContainerGap(361, Short.MAX_VALUE))
        );

        denialList.setOpaque(false);

        welcome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcome.setForeground(new java.awt.Color(102, 102, 102));
        welcome.setText("Welcome, ");

        logoutButton.setBackground(new java.awt.Color(0, 153, 153));
        logoutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(102, 102, 102));
        logoutButton.setText("Logout");
        logoutButton.setOpaque(false);
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                returnToLogin(evt);
            }
        });

        denialListPanel.setBackground(new java.awt.Color(204, 255, 204));
        denialListPanel.setOpaque(false);

        titlePanel.setBackground(new java.awt.Color(0, 153, 153));

        patientNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        patientNameLabel.setForeground(new java.awt.Color(204, 255, 204));
        patientNameLabel.setText("Patient Name");
        patientNameLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));

        insuranceNameLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        insuranceNameLabel.setForeground(new java.awt.Color(204, 255, 204));
        insuranceNameLabel.setText("Insurance");

        denialReasonLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        denialReasonLabel.setForeground(new java.awt.Color(204, 255, 204));
        denialReasonLabel.setText("Denial Reason");

        dosLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dosLabel.setForeground(new java.awt.Color(204, 255, 204));
        dosLabel.setText("DOS");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addComponent(patientNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(insuranceNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(denialReasonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(patientNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addComponent(insuranceNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(denialReasonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dosLabel))
        );

        denialScrollPane.setBorder(null);
        denialScrollPane.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        denialScrollPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        denialListList.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        denialListList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        denialListList.setForeground(new java.awt.Color(0, 153, 153));
        denialListList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Patient1", "Patient2", "Patient3", "Patient4", "Patient5", "Patient6", "Patient7", "Patient8", "Patient9", "Patient10", "Patient1", "Patient2", "Patient3", "Patient4", "Patient5", "Patient6", "Patient7", "Patient8", "Patient9", "Patient10", "Patient1", "Patient2", "Patient3", "Patient4", "Patient5", "Patient6", "Patient7", "Patient8", "Patient9", "Patient10", "Patient1", "Patient2", "Patient3", "Patient4", "Patient5", "Patient6", "Patient7", "Patient8", "Patient9", "Patient10" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        denialListList.setFixedCellHeight(20);
        denialListList.setSelectionBackground(new java.awt.Color(0, 204, 204));
        denialListList.setValueIsAdjusting(true);
        denialListList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                denialListListMouseClicked(evt);
            }
        });
        denialScrollPane.setViewportView(denialListList);

        javax.swing.GroupLayout denialListPanelLayout = new javax.swing.GroupLayout(denialListPanel);
        denialListPanel.setLayout(denialListPanelLayout);
        denialListPanelLayout.setHorizontalGroup(
            denialListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(denialScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        denialListPanelLayout.setVerticalGroup(
            denialListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(denialListPanelLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(denialScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout denialListLayout = new javax.swing.GroupLayout(denialList);
        denialList.setLayout(denialListLayout);
        denialListLayout.setHorizontalGroup(
            denialListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(denialListLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(denialListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(denialListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(denialListLayout.createSequentialGroup()
                        .addComponent(welcome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        denialListLayout.setVerticalGroup(
            denialListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, denialListLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(denialListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(denialListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        letterGenPanel.setOpaque(false);
        letterGenPanel.setPreferredSize(new java.awt.Dimension(1299, 841));

        welcome1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        welcome1.setForeground(new java.awt.Color(102, 102, 102));
        welcome1.setText("Welcome, ");

        logoutButton1.setBackground(new java.awt.Color(0, 153, 153));
        logoutButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutButton1.setForeground(new java.awt.Color(102, 102, 102));
        logoutButton1.setText("Logout");
        logoutButton1.setOpaque(false);
        logoutButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnToLogin(evt);
            }
        });

        letterGenTransBgPanel.setBackground(new java.awt.Color(255, 255, 255));

        ptNameLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ptNameLabel.setForeground(new java.awt.Color(0, 153, 153));
        ptNameLabel.setText("Patient Name:");

        ptDosLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ptDosLabel.setForeground(new java.awt.Color(0, 153, 153));
        ptDosLabel.setText("Date of Service:");

        procLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        procLabel.setForeground(new java.awt.Color(0, 153, 153));
        procLabel.setText("Procedure:");

        dxLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dxLabel.setForeground(new java.awt.Color(0, 153, 153));
        dxLabel.setText("Diagnosis:");

        attPhysLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        attPhysLabel.setForeground(new java.awt.Color(0, 153, 153));
        attPhysLabel.setText("Attending Physician:");

        jSeparator1.setForeground(new java.awt.Color(0, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        insCoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        insCoLabel.setForeground(new java.awt.Color(0, 153, 153));
        insCoLabel.setText("Insurance Company:");

        insCoAdd1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        insCoAdd1.setForeground(new java.awt.Color(0, 153, 153));
        insCoAdd1.setText("Address: (line1)");

        insCoAdd2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        insCoAdd2.setForeground(new java.awt.Color(0, 153, 153));
        insCoAdd2.setText("(line2)");

        insCoAdd3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        insCoAdd3.setForeground(new java.awt.Color(0, 153, 153));
        insCoAdd3.setText("(line3/city,state zip)");

        insCoLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        insCoLabel1.setForeground(new java.awt.Color(0, 153, 153));
        insCoLabel1.setText("Policy Number:");

        jSeparator2.setForeground(new java.awt.Color(0, 153, 153));

        ptDenialReasonLabel.setBackground(new java.awt.Color(0, 153, 153));
        ptDenialReasonLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ptDenialReasonLabel.setForeground(new java.awt.Color(0, 153, 153));
        ptDenialReasonLabel.setText("Denial Reason: ");

        preGenAppealReasonLabel.setBackground(new java.awt.Color(0, 153, 153));
        preGenAppealReasonLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        preGenAppealReasonLabel.setForeground(new java.awt.Color(0, 153, 153));
        preGenAppealReasonLabel.setText("Appeal Reason: ");

        preGenAppealReasons.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        preGenAppealReasons.setForeground(new java.awt.Color(0, 153, 153));
        preGenAppealReasons.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reason1", "Reason2", "Reason3", "Reason4" }));

        preGenAppealReasonLabel1.setBackground(new java.awt.Color(0, 153, 153));
        preGenAppealReasonLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        preGenAppealReasonLabel1.setForeground(new java.awt.Color(0, 153, 153));
        preGenAppealReasonLabel1.setText("New Appeal:");

        newAppealTitleTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        newAppealTitleTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        newAppealTitleTextField.setSelectionColor(new java.awt.Color(0, 153, 153));

        jTextPane1.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        jScrollPane2.setViewportView(jTextPane1);

        saveAppealReasonCheckBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveAppealReasonCheckBox.setForeground(new java.awt.Color(0, 153, 153));
        saveAppealReasonCheckBox.setText("Save Entry?");
        saveAppealReasonCheckBox.setContentAreaFilled(false);
        saveAppealReasonCheckBox.setFocusPainted(false);
        saveAppealReasonCheckBox.setFocusable(false);
        saveAppealReasonCheckBox.setRequestFocusEnabled(false);
        saveAppealReasonCheckBox.setRolloverEnabled(false);
        saveAppealReasonCheckBox.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout letterGenTransBgPanelLayout = new javax.swing.GroupLayout(letterGenTransBgPanel);
        letterGenTransBgPanel.setLayout(letterGenTransBgPanelLayout);
        letterGenTransBgPanelLayout.setHorizontalGroup(
            letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letterGenTransBgPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveAppealReasonCheckBox)
                    .addGroup(letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane2)
                        .addComponent(jSeparator2)
                        .addGroup(letterGenTransBgPanelLayout.createSequentialGroup()
                            .addGroup(letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ptNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ptDosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(procLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(attPhysLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(insCoAdd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(insCoLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(insCoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                                .addGroup(letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(insCoAdd3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                                    .addComponent(insCoAdd2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addComponent(ptDenialReasonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(letterGenTransBgPanelLayout.createSequentialGroup()
                            .addGroup(letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(preGenAppealReasonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(preGenAppealReasonLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newAppealTitleTextField)
                                .addComponent(preGenAppealReasons, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(35, 35, 35))
        );
        letterGenTransBgPanelLayout.setVerticalGroup(
            letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letterGenTransBgPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(letterGenTransBgPanelLayout.createSequentialGroup()
                        .addComponent(insCoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insCoAdd1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insCoAdd2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insCoAdd3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insCoLabel1))
                    .addComponent(jSeparator1)
                    .addGroup(letterGenTransBgPanelLayout.createSequentialGroup()
                        .addComponent(ptNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ptDosLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(procLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dxLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attPhysLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ptDenialReasonLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preGenAppealReasonLabel)
                    .addComponent(preGenAppealReasons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(letterGenTransBgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preGenAppealReasonLabel1)
                    .addComponent(newAppealTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveAppealReasonCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        backButton.setBackground(new java.awt.Color(0, 153, 153));
        backButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(102, 102, 102));
        backButton.setText("Back");
        backButton.setOpaque(false);
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnToList(evt);
            }
        });

        submit.setBackground(new java.awt.Color(0, 153, 153));
        submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(102, 102, 102));
        submit.setText("Submit");
        submit.setOpaque(false);
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitAppeal(evt);
            }
        });

        coInsButton.setBackground(new java.awt.Color(0, 153, 153));
        coInsButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        coInsButton.setForeground(new java.awt.Color(102, 102, 102));
        coInsButton.setText("Co Ins");
        coInsButton.setOpaque(false);
        coInsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientResponsibility(evt);
            }
        });

        javax.swing.GroupLayout letterGenPanelLayout = new javax.swing.GroupLayout(letterGenPanel);
        letterGenPanel.setLayout(letterGenPanelLayout);
        letterGenPanelLayout.setHorizontalGroup(
            letterGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letterGenPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(letterGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(letterGenPanelLayout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coInsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(letterGenPanelLayout.createSequentialGroup()
                        .addComponent(welcome1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(letterGenTransBgPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        letterGenPanelLayout.setVerticalGroup(
            letterGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(letterGenPanelLayout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addGroup(letterGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(letterGenTransBgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(letterGenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coInsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(denialList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(letterGenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(denialList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(letterGenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(kGradientPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusGained
        // TODO add your handling code here:
        if(username.getText().equals("Username")){
            username.setText("");
            username.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_usernameFocusGained

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
        // TODO add your handling code here:
        if(username.getText().equals("")){
            username.setText("Username");
            username.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        // TODO add your handling code here:
        if(String.valueOf(password.getPassword()).equals("Password")){
            password.setText("");
            password.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_passwordFocusGained

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        // TODO add your handling code here:
        if(String.valueOf(password.getPassword()).equals("")){
            password.setText("Password");
            password.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_passwordFocusLost

    private void LoginButtonClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonClicked

        // This is where we take the username and password strings to connect to the DB
        // will need to add a new class for the 'controller' with MVC format
        
        // add code for if connection to db = true, loginpanel.setvisible(false)
        // currently always showing the result of a true db connection
        loginPanel.setVisible(false);
        denialList.setVisible(true);
        setTitle("Denial Appeal System - Denial List");
        
        
        
        //if connection could not be established, connErr.setVisible(true);
        
    }//GEN-LAST:event_LoginButtonClicked

    private void returnToLogin(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnToLogin
        // TODO add your handling code here:
        // will need to add component that disconnects from db
        if (denialList.isVisible()){
            denialList.setVisible(false);
            setTitle("Denial Appeal System - Login");
            loginPanel.setVisible(true);
        }
        if (letterGenPanel.isVisible()){
            letterGenPanel.setVisible(false);
            setTitle("Denial Appeal System - Login");
            loginPanel.setVisible(true);
        }
    }//GEN-LAST:event_returnToLogin

    private void denialListListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_denialListListMouseClicked
        // TODO add your handling code here:
        javax.swing.JList<String> tmpClickItem = (javax.swing.JList) evt.getSource();
        if (evt.getClickCount()== 2){
            denialList.setVisible(false);
            letterGenPanel.setVisible(true);
            setTitle("Denial Appeal System - Letter Generation");
            int index = tmpClickItem.locationToIndex(evt.getPoint());
            if (index >= 0) {
                Object o = tmpClickItem.getModel().getElementAt(index);
                System.out.println("Double-clicked on: " + o.toString()); //remove with functionality, temporary placeholder of list item that was selected
            }
        }
        
    }//GEN-LAST:event_denialListListMouseClicked

    private void returnToList(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnToList
        // TODO add your handling code here:
        letterGenPanel.setVisible(false);
        denialList.setVisible(true);
        //add code to generate a new list from the db
        setTitle("Denial Appeal System - Denial List");
    }//GEN-LAST:event_returnToList

    private void submitAppeal(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitAppeal
        // TODO add your handling code here:
        //calls generateDocument() and updateClaimStatus()
        //if a new appeal reason was added, calls newAppeal() to save info
        //in db
        letterGenPanel.setVisible(false);
        denialList.setVisible(true);
        //add code to generate a new list from the db
        setTitle("Denial Appeal System - Denial List");
    }//GEN-LAST:event_submitAppeal

    private void patientResponsibility(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientResponsibility
        // TODO add your handling code here:
        letterGenPanel.setVisible(false);
        denialList.setVisible(true);
        //add code to change the claim status in DB
        //add code to generate a new list from the db
        setTitle("Denial Appeal System - Denial List");
    }//GEN-LAST:event_patientResponsibility

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DenialAppealSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DenialAppealSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DenialAppealSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DenialAppealSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DenialAppealSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel attPhysLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton coInsButton;
    private javax.swing.JLabel connErr;
    private javax.swing.JPanel denialList;
    private javax.swing.JList<String> denialListList;
    private javax.swing.JPanel denialListPanel;
    private javax.swing.JLabel denialReasonLabel;
    private javax.swing.JScrollPane denialScrollPane;
    private javax.swing.JLabel dosLabel;
    private javax.swing.JLabel dxLabel;
    private javax.swing.JLabel insCoAdd1;
    private javax.swing.JLabel insCoAdd2;
    private javax.swing.JLabel insCoAdd3;
    private javax.swing.JLabel insCoLabel;
    private javax.swing.JLabel insCoLabel1;
    private javax.swing.JLabel insuranceNameLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextPane jTextPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPanel letterGenPanel;
    private javax.swing.JPanel letterGenTransBgPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton logoutButton1;
    private javax.swing.JTextField newAppealTitleTextField;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel patientNameLabel;
    private javax.swing.JLabel preGenAppealReasonLabel;
    private javax.swing.JLabel preGenAppealReasonLabel1;
    private javax.swing.JComboBox<String> preGenAppealReasons;
    private javax.swing.JLabel procLabel;
    private javax.swing.JLabel ptDenialReasonLabel;
    private javax.swing.JLabel ptDosLabel;
    private javax.swing.JLabel ptNameLabel;
    private javax.swing.JCheckBox saveAppealReasonCheckBox;
    private javax.swing.JButton submit;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel userIcon;
    private javax.swing.JTextField username;
    private javax.swing.JLabel welcome;
    private javax.swing.JLabel welcome1;
    // End of variables declaration//GEN-END:variables
}
